site_name: CiviSEPA PSP
repo_url: https://github.com/systopia/de.systopia.pspsepa
theme: material

pages:
- 'Overview': index.md
- 'Supported PSP': supported-psp.md
- 'Getting started': getting-started.md
- 'Usage': usage.md

markdown_extensions:
- attr_list
- admonition
- def_list
- codehilite
- toc:
    permalink: true
- pymdownx.superfences
- pymdownx.inlinehilite
- pymdownx.tilde
- pymdownx.betterem
- pymdownx.mark
